### ISSUE TITLE
confusing symbol in 3.3

### ISSUE THREAD

**Issue by yangam16** [AIR-THU/UniV2X#1]
Hi, thanks for your excellent work.
Maybe there is something wrong in page 6, 3.3 Sparse-Dense Hybrid Data Generation? In the sentense of "During transmission, we filter out low-scoring queries using boxes generated from the classification decoder, and exclusively transmit {N^inf_l} valid lane queries {Q^veh_L}". I wonder whether the symbol of lane queries should "Q^INF_L" rathan than "Q^veh_L".
Thanks a lot.

**Comment by haibao-yu** [comment]
Hi, thanks for your feedback. It is a typo error and it should be "Q^INF_L" rathan than "Q^veh_L". We will update a new version.
